# Generated by Django 3.2.4 on 2021-06-18 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('unique_id', models.CharField(default='', max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('difficulty', models.CharField(choices=[('ES', 'Easy'), ('MD', 'Medium'), ('HD', 'Hard'), ('VH', 'Very Hard'), ('EX', 'Expert')], default='MD', max_length=2)),
                ('curation_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IA', 'Inactive')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DsAlgoTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DS', 'Data Structures'), ('AL', 'Algorithms')], default='DS', max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('CU', 'Curator'), ('LR', 'Learner')], default='LR', max_length=2)),
                ('bio', models.CharField(default=' ', max_length=100)),
                ('total_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('curation_time', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('ES', 'Easy'), ('MD', 'Medium'), ('HD', 'Hard'), ('VH', 'Very Hard'), ('EX', 'Expert')], default='MD', max_length=2)),
                ('score', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.dsalgotopics')),
                ('contest_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.contest')),
                ('prof_w_c', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('test_cases', models.TextField()),
                ('input_cases', models.TextField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='SolvedOrNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.profile')),
                ('probs', models.ManyToManyField(to='sub_app.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('_contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.contest')),
                ('_ques', models.ManyToManyField(blank=True, to='sub_app.Question')),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='NormalProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('test_cases', models.TextField()),
                ('input_cases', models.TextField(blank=True, null=True)),
                ('curation_time', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('ES', 'Easy'), ('MD', 'Medium'), ('HD', 'Hard'), ('VH', 'Very Hard'), ('EX', 'Expert')], default='MD', max_length=2)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.dsalgotopics')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_app.profile'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IA', 'Inactive')], default='AC', max_length=2)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sub_app.profile')),
                ('questions', models.ManyToManyField(to='sub_app.Question')),
            ],
        ),
    ]
