# Generated by Django 3.2.4 on 2021-06-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('test_cases', models.TextField()),
                ('input_cases', models.TextField()),
                ('curation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
