# Generated by Django 3.2.4 on 2021-06-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DsAlgoTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DS', 'Data Structures'), ('AL', 'Algorithms')], default='DS', max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('ES', 'Easy'), ('MD', 'Medium'), ('HD', 'Hard'), ('VH', 'Very Hard'), ('EX', 'Expert')], default='MD', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_cases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.dsalgotopics'),
        ),
    ]
