# Generated by Django 3.2.4 on 2021-06-07 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0002_auto_20210607_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('difficulty', models.CharField(choices=[('ES', 'Easy'), ('MD', 'Medium'), ('HD', 'Hard'), ('VH', 'Very Hard'), ('EX', 'Expert')], default='MD', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='contest_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.contest'),
        ),
    ]
