# Generated by Django 3.2.4 on 2021-06-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0003_scorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
