# Generated by Django 3.2.4 on 2021-06-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0003_auto_20210608_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='curation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='unique_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
