# Generated by Django 3.2.4 on 2021-06-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0004_question_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='_ques',
            field=models.ManyToManyField(blank=True, null=True, to='sub_app.Question'),
        ),
    ]
