# Generated by Django 3.2.4 on 2021-06-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0005_scorecard__ques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='_ques',
            field=models.ManyToManyField(blank=True, to='sub_app.Question'),
        ),
    ]
