# Generated by Django 3.2.4 on 2021-06-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0006_alter_scorecard__ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
