# Generated by Django 3.2.4 on 2021-06-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0009_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('test_cases', models.TextField()),
                ('input_cases', models.TextField(blank=True, null=True)),
                ('curation_time', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('ES', 'Easy'), ('MD', 'Medium'), ('HD', 'Hard'), ('VH', 'Very Hard'), ('EX', 'Expert')], default='MD', max_length=2)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.dsalgotopics')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_app.profile')),
            ],
        ),
    ]
