# Generated by Django 3.2.4 on 2021-06-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0010_normalproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prof_w_c',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.profile'),
        ),
    ]
