# Generated by Django 3.2.4 on 2021-06-15 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0011_question_prof_w_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedOrNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.profile')),
                ('probs', models.ManyToManyField(to='sub_app.Question')),
            ],
        ),
    ]
