# Generated by Django 3.2.4 on 2021-06-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0013_bookmark_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='type',
            new_name='_type',
        ),
    ]
