# Generated by Django 3.2.4 on 2021-06-21 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub_app', '0002_alter_question_prof_w_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('PR', 'Private'), ('PB', 'Public')], default='PB', max_length=2)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='members', to='sub_app.Profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('chatter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_app.profile')),
                ('room_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_section.room')),
            ],
        ),
    ]
